#ifndef VS1053_INSTRUMENTS_H

#define HIGH_Q 27
#define SLAP 28
#define SCRATCH_PUSH 29 // EXC7
#define SCRATCH_PULL 30 // EXC7
#define STICKS 31
#define SQUARE_CLICK 32
#define METRONOME_CLICK 33
#define METRONOME_BELL 34
#define ACOUSTIC_BASS_DRUM 35
#define BASS_DRUM_1 36
#define SIDE_STICK 37
#define ACOUSTIC_SNARE 38
#define HAND_CLAP 39
#define ELECTRIC_SNARE 40
#define LOW_FLOOR_TOM 41
#define CLOSED_HI_HAT 42 // EXC1
#define HIGH_FLOOR_TOM 43
#define PEDAL_HI_HAT 44 // EXC1
#define LOW_TOM 45
#define OPEN_HI_HAT 46 // EXC1
#define LOW_MID_TOM 47
#define HIGH_MID_TOM 48
#define CRASH_CYMBAL_1 49
#define HIGH_TOM 50
#define RIDE_CYMBAL_1 51
#define CHINESE_CYMBAL 52
#define RIDE_BELL 53
#define TAMBOURINE 54
#define SPLASH_CYMBAL 55
#define COWBELL 56
#define CRASH_CYMBAL_2 57
#define VIBRA_SLAP 58
#define RIDE_CYMBAL_2 59
#define HIGH_BONGO 60
#define LOW_BONGO 61
#define MUTE_HI_CONGA 62
#define OPEN_HI_CONGA 63
#define LOW_CONGA 64
#define HIGH_TIMBALE 65
#define LOW_TIMBALE 66
#define HIGH_AGOGO 67
#define LOW_AGOGO 68
#define CABASA 69
#define MARACAS 70
#define SHORT_WHISTLE 71 //EXC2
#define LONG_WHISTLE 2 72 // EXC2
#define SHORT_GUIRO 73 // EXC3
#define LONG_GUIRO 74 // EXC3
#define CLAVES 75
#define HI_WOOD_BLOCK 76
#define LOW_WOOD_BLOCK 77
#define MUTE_CUICA 78 // EXC4
#define OPEN_CUICA 79 // EXC4
#define MUTE_TRIANGLE 80 // EXC5
#define OPEN_TRIANGLE 81 // EXC5
#define SHAKER 82
#define JINGLE_BELL 83
#define BELL_TREE 84
#define CASTANETS 85
#define MUTE_SURDO 86 // EXC6
#define OPEN_SURDO 87 // EXC6
#endif